apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
    name: pv
    PersistentVolumeClaim:
      claimName: task-pv-claim
  containers:
  - name: nginx-cont
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/mginx/html
      