apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    env:
    - name: ENVIRONMENT
      valueFrom:
        configMapRef:
          name: keyvalcfgmap
          key: var1