apiVersion: v1
kind: Pod
metadata:
  
  labels:
    run: nginx
  name: nginxpodd
spec:
  containers:
  - image: nginx
    securityContext:
      capabilities:
        add: ["SYS_TIME", "NET_ADMIN"]
    name: nginx
    