apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-cont-pod
  name: multi-cont-pod
  namespace: default
spec:
  volumes: 
  - name: var-logs
    emptyDir: {}
  containers:
  - image: busybox
    command: ["/bin/sh"]
    name: busybox-main
    args: 
      - -c
      - while true
      - do echo 'Hi I am from Main container' >> /var/log/index.html
      - sleep 5
      - done
    volumeMounts:
    - name: var-logs
      mountPath: /var/log
    resources: {}

  - image: nginx
    name: sidecar
    ports:
      - containerPort: 80
    resources: {}
    volumeMounts:
    - name: var-logs
      mountPath: /usr/share/mginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
